# Generated by Django 3.0.5 on 2020-05-15 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherExtra',
        ),
    ]
