# Generated by Django 3.0.5 on 2020-05-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0007_auto_20200520_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='DoctorProfilePic/'),
        ),
    ]
