# Generated by Django 3.0.5 on 2021-03-30 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_doctor_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('date', models.DateField(auto_now=True)),
                ('current_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_hospital', to='hospital.Hospital')),
                ('new_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_hospital', to='hospital.Hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient')),
            ],
        ),
    ]
