# Generated by Django 3.0.5 on 2021-04-10 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20210410_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
