# Generated by Django 3.0.5 on 2021-04-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0027_auto_20210410_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
